
package org.oasis.wsrp.v2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WSRPService", targetNamespace = "urn:oasis:names:tc:wsrp:v2:wsdl", wsdlLocation = "file:/Users/claprun/Dev/gatein/components/wsrp/trunk/wsrp2-ws/src/main/resources/wsrp/wsrp-2.0-services.wsdl")
public class WSRPService
    extends Service
{

    private final static URL WSRPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.oasis.wsrp.v2.WSRPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.oasis.wsrp.v2.WSRPService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/claprun/Dev/gatein/components/wsrp/trunk/wsrp2-ws/src/main/resources/wsrp/wsrp-2.0-services.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/claprun/Dev/gatein/components/wsrp/trunk/wsrp2-ws/src/main/resources/wsrp/wsrp-2.0-services.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSRPSERVICE_WSDL_LOCATION = url;
    }

    public WSRPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSRPService() {
        super(WSRPSERVICE_WSDL_LOCATION, new QName("urn:oasis:names:tc:wsrp:v2:wsdl", "WSRPService"));
    }

    /**
     * 
     * @return
     *     returns WSRPV2MarkupPortType
     */
    @WebEndpoint(name = "WSRPBaseService")
    public WSRPV2MarkupPortType getWSRPBaseService() {
        return super.getPort(new QName("urn:oasis:names:tc:wsrp:v2:wsdl", "WSRPBaseService"), WSRPV2MarkupPortType.class);
    }

    /**
     * 
     * @return
     *     returns WSRPV2ServiceDescriptionPortType
     */
    @WebEndpoint(name = "WSRPServiceDescriptionService")
    public WSRPV2ServiceDescriptionPortType getWSRPServiceDescriptionService() {
        return super.getPort(new QName("urn:oasis:names:tc:wsrp:v2:wsdl", "WSRPServiceDescriptionService"), WSRPV2ServiceDescriptionPortType.class);
    }

    /**
     * 
     * @return
     *     returns WSRPV2RegistrationPortType
     */
    @WebEndpoint(name = "WSRPRegistrationService")
    public WSRPV2RegistrationPortType getWSRPRegistrationService() {
        return super.getPort(new QName("urn:oasis:names:tc:wsrp:v2:wsdl", "WSRPRegistrationService"), WSRPV2RegistrationPortType.class);
    }

    /**
     * 
     * @return
     *     returns WSRPV2PortletManagementPortType
     */
    @WebEndpoint(name = "WSRPPortletManagementService")
    public WSRPV2PortletManagementPortType getWSRPPortletManagementService() {
        return super.getPort(new QName("urn:oasis:names:tc:wsrp:v2:wsdl", "WSRPPortletManagementService"), WSRPV2PortletManagementPortType.class);
    }

}
