
package org.oasis.wsrp.v2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSRP_v2_Markup_PortType", targetNamespace = "urn:oasis:names:tc:wsrp:v2:intf")
public interface WSRPV2MarkupPortType {


    /**
     * 
     * @param sessionContext
     * @param runtimeContext
     * @param markupContext
     * @param registrationContext
     * @param markupParams
     * @param portletContext
     * @param userContext
     * @param extensions
     * @throws UnsupportedMode
     * @throws OperationFailed
     * @throws InconsistentParameters
     * @throws MissingParameters
     * @throws UnsupportedMimeType
     * @throws InvalidCookie
     * @throws ModifyRegistrationRequired
     * @throws AccessDenied
     * @throws ResourceSuspended
     * @throws UnsupportedWindowState
     * @throws InvalidUserCategory
     * @throws UnsupportedLocale
     * @throws InvalidSession
     * @throws InvalidHandle
     * @throws InvalidRegistration
     */
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v2:getMarkup")
    @RequestWrapper(localName = "getMarkup", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.GetMarkup")
    @ResponseWrapper(localName = "getMarkupResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.MarkupResponse")
    public void getMarkup(
        @WebParam(name = "registrationContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RegistrationContext registrationContext,
        @WebParam(name = "portletContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        PortletContext portletContext,
        @WebParam(name = "runtimeContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RuntimeContext runtimeContext,
        @WebParam(name = "userContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        UserContext userContext,
        @WebParam(name = "markupParams", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        MarkupParams markupParams,
        @WebParam(name = "markupContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<MarkupContext> markupContext,
        @WebParam(name = "sessionContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<SessionContext> sessionContext,
        @WebParam(name = "extensions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<List<Extension>> extensions)
        throws AccessDenied, InconsistentParameters, InvalidCookie, InvalidHandle, InvalidRegistration, InvalidSession, InvalidUserCategory, MissingParameters, ModifyRegistrationRequired, OperationFailed, ResourceSuspended, UnsupportedLocale, UnsupportedMimeType, UnsupportedMode, UnsupportedWindowState
    ;

    /**
     * 
     * @param sessionContext
     * @param runtimeContext
     * @param registrationContext
     * @param portletContext
     * @param resourceContext
     * @param resourceParams
     * @param userContext
     * @param extensions
     * @throws UnsupportedMode
     * @throws OperationFailed
     * @throws InconsistentParameters
     * @throws MissingParameters
     * @throws UnsupportedMimeType
     * @throws InvalidCookie
     * @throws ModifyRegistrationRequired
     * @throws AccessDenied
     * @throws ResourceSuspended
     * @throws UnsupportedWindowState
     * @throws InvalidUserCategory
     * @throws UnsupportedLocale
     * @throws InvalidSession
     * @throws OperationNotSupported
     * @throws InvalidHandle
     * @throws InvalidRegistration
     */
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v2:getResource")
    @RequestWrapper(localName = "getResource", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.GetResource")
    @ResponseWrapper(localName = "getResourceResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.ResourceResponse")
    public void getResource(
        @WebParam(name = "registrationContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RegistrationContext registrationContext,
        @WebParam(name = "portletContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.INOUT)
        Holder<PortletContext> portletContext,
        @WebParam(name = "runtimeContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RuntimeContext runtimeContext,
        @WebParam(name = "userContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        UserContext userContext,
        @WebParam(name = "resourceParams", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        ResourceParams resourceParams,
        @WebParam(name = "resourceContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<ResourceContext> resourceContext,
        @WebParam(name = "sessionContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<SessionContext> sessionContext,
        @WebParam(name = "extensions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<List<Extension>> extensions)
        throws AccessDenied, InconsistentParameters, InvalidCookie, InvalidHandle, InvalidRegistration, InvalidSession, InvalidUserCategory, MissingParameters, ModifyRegistrationRequired, OperationFailed, OperationNotSupported, ResourceSuspended, UnsupportedLocale, UnsupportedMimeType, UnsupportedMode, UnsupportedWindowState
    ;

    /**
     * 
     * @param runtimeContext
     * @param registrationContext
     * @param redirectURL
     * @param updateResponse
     * @param markupParams
     * @param portletContext
     * @param interactionParams
     * @param userContext
     * @param extensions
     * @throws PortletStateChangeRequired
     * @throws OperationFailed
     * @throws UnsupportedMode
     * @throws InconsistentParameters
     * @throws MissingParameters
     * @throws UnsupportedMimeType
     * @throws InvalidCookie
     * @throws ModifyRegistrationRequired
     * @throws AccessDenied
     * @throws ResourceSuspended
     * @throws UnsupportedWindowState
     * @throws InvalidUserCategory
     * @throws UnsupportedLocale
     * @throws InvalidSession
     * @throws InvalidHandle
     * @throws InvalidRegistration
     */
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v2:performBlockingInteraction")
    @RequestWrapper(localName = "performBlockingInteraction", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.PerformBlockingInteraction")
    @ResponseWrapper(localName = "performBlockingInteractionResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.BlockingInteractionResponse")
    public void performBlockingInteraction(
        @WebParam(name = "registrationContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RegistrationContext registrationContext,
        @WebParam(name = "portletContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        PortletContext portletContext,
        @WebParam(name = "runtimeContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RuntimeContext runtimeContext,
        @WebParam(name = "userContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        UserContext userContext,
        @WebParam(name = "markupParams", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        MarkupParams markupParams,
        @WebParam(name = "interactionParams", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        InteractionParams interactionParams,
        @WebParam(name = "updateResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<UpdateResponse> updateResponse,
        @WebParam(name = "redirectURL", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<String> redirectURL,
        @WebParam(name = "extensions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<List<Extension>> extensions)
        throws AccessDenied, InconsistentParameters, InvalidCookie, InvalidHandle, InvalidRegistration, InvalidSession, InvalidUserCategory, MissingParameters, ModifyRegistrationRequired, OperationFailed, PortletStateChangeRequired, ResourceSuspended, UnsupportedLocale, UnsupportedMimeType, UnsupportedMode, UnsupportedWindowState
    ;

    /**
     * 
     * @param runtimeContext
     * @param registrationContext
     * @param updateResponse
     * @param markupParams
     * @param portletContext
     * @param userContext
     * @param failedEvents
     * @param extensions
     * @param eventParams
     * @throws PortletStateChangeRequired
     * @throws OperationFailed
     * @throws UnsupportedMode
     * @throws InconsistentParameters
     * @throws MissingParameters
     * @throws UnsupportedMimeType
     * @throws InvalidCookie
     * @throws ModifyRegistrationRequired
     * @throws AccessDenied
     * @throws ResourceSuspended
     * @throws UnsupportedWindowState
     * @throws InvalidUserCategory
     * @throws UnsupportedLocale
     * @throws OperationNotSupported
     * @throws InvalidSession
     * @throws InvalidHandle
     * @throws InvalidRegistration
     */
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v2:handleEvents")
    @RequestWrapper(localName = "handleEvents", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.HandleEvents")
    @ResponseWrapper(localName = "handleEventsResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.HandleEventsResponse")
    public void handleEvents(
        @WebParam(name = "registrationContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RegistrationContext registrationContext,
        @WebParam(name = "portletContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        PortletContext portletContext,
        @WebParam(name = "runtimeContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RuntimeContext runtimeContext,
        @WebParam(name = "userContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        UserContext userContext,
        @WebParam(name = "markupParams", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        MarkupParams markupParams,
        @WebParam(name = "eventParams", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        EventParams eventParams,
        @WebParam(name = "updateResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<UpdateResponse> updateResponse,
        @WebParam(name = "failedEvents", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<List<HandleEventsFailed>> failedEvents,
        @WebParam(name = "extensions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", mode = WebParam.Mode.OUT)
        Holder<List<Extension>> extensions)
        throws AccessDenied, InconsistentParameters, InvalidCookie, InvalidHandle, InvalidRegistration, InvalidSession, InvalidUserCategory, MissingParameters, ModifyRegistrationRequired, OperationFailed, OperationNotSupported, PortletStateChangeRequired, ResourceSuspended, UnsupportedLocale, UnsupportedMimeType, UnsupportedMode, UnsupportedWindowState
    ;

    /**
     * 
     * @param registrationContext
     * @param userContext
     * @param sessionIDs
     * @return
     *     returns java.util.List<org.oasis.wsrp.v2.Extension>
     * @throws OperationFailed
     * @throws MissingParameters
     * @throws ModifyRegistrationRequired
     * @throws OperationNotSupported
     * @throws AccessDenied
     * @throws InvalidRegistration
     * @throws ResourceSuspended
     */
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v2:releaseSessions")
    @WebResult(name = "extensions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
    @RequestWrapper(localName = "releaseSessions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.ReleaseSessions")
    @ResponseWrapper(localName = "releaseSessionsResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.ReturnAny")
    public List<Extension> releaseSessions(
        @WebParam(name = "registrationContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RegistrationContext registrationContext,
        @WebParam(name = "sessionIDs", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        List<String> sessionIDs,
        @WebParam(name = "userContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        UserContext userContext)
        throws AccessDenied, InvalidRegistration, MissingParameters, ModifyRegistrationRequired, OperationFailed, OperationNotSupported, ResourceSuspended
    ;

    /**
     * 
     * @param registrationContext
     * @param userContext
     * @return
     *     returns java.util.List<org.oasis.wsrp.v2.Extension>
     * @throws OperationFailed
     * @throws ModifyRegistrationRequired
     * @throws OperationNotSupported
     * @throws AccessDenied
     * @throws InvalidRegistration
     * @throws ResourceSuspended
     */
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v2:initCookie")
    @WebResult(name = "extensions", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
    @RequestWrapper(localName = "initCookie", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.InitCookie")
    @ResponseWrapper(localName = "initCookieResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types", className = "org.oasis.wsrp.v2.ReturnAny")
    public List<Extension> initCookie(
        @WebParam(name = "registrationContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        RegistrationContext registrationContext,
        @WebParam(name = "userContext", targetNamespace = "urn:oasis:names:tc:wsrp:v2:types")
        UserContext userContext)
        throws AccessDenied, InvalidRegistration, ModifyRegistrationRequired, OperationFailed, OperationNotSupported, ResourceSuspended
    ;

}
