<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ JBoss, a division of Red Hat
  ~ Copyright 2009, Red Hat Middleware, LLC, and individual
  ~ contributors as indicated by the @authors tag. See the
  ~ copyright.txt in the distribution for a full listing of
  ~ individual contributors.
  ~
  ~ This is free software; you can redistribute it and/or modify it
  ~ under the terms of the GNU Lesser General Public License as
  ~ published by the Free Software Foundation; either version 2.1 of
  ~ the License, or (at your option) any later version.
  ~
  ~ This software is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this software; if not, write to the Free
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<wsdl:definitions targetNamespace="urn:oasis:names:tc:wsrp:v1:wsdl"
                  xmlns:bind="urn:oasis:names:tc:wsrp:v1:bind"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:intf="urn:oasis:names:tc:wsrp:v1:intf"
                  xmlns:tns="urn:oasis:names:tc:wsrp:v1:wsdl">

   <import namespace="urn:oasis:names:tc:wsrp:v1:bind" location="wsrp_v1_bindings.wsdl"/>

   <wsdl:service name="WSRPService">
      <wsdl:port binding="bind:WSRP_v1_Markup_Binding_SOAP" name="WSRPMarkupService">
         <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
      </wsdl:port>

      <wsdl:port binding="bind:WSRP_v1_ServiceDescription_Binding_SOAP" name="WSRPServiceDescriptionService">
         <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
      </wsdl:port>

      <wsdl:port binding="bind:WSRP_v1_Registration_Binding_SOAP" name="WSRPRegistrationService">
         <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
      </wsdl:port>

      <wsdl:port binding="bind:WSRP_v1_PortletManagement_Binding_SOAP" name="WSRPPortletManagementService">
         <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
      </wsdl:port>
   </wsdl:service>

   <!--
      Uncomment to use HTTP+SSL after activating the appropriate Tomcat Connector and comment out the above service
      definition. Adapt host name and port as appropriate.
   <wsdl:service name="WSRPService">
      <wsdl:port binding="bind:WSRP_v1_Markup_Binding_SOAP" name="WSRPBaseService">
         <soap:address location="https://localhost:8443/portal-wsrp/ServiceDescriptionService"/>
      </wsdl:port>

      <wsdl:port binding="bind:WSRP_v1_ServiceDescription_Binding_SOAP" name="WSRPServiceDescriptionService">
         <soap:address location="https://localhost:8443/portal-wsrp/MarkupService"/>
      </wsdl:port>

      <wsdl:port binding="bind:WSRP_v1_Registration_Binding_SOAP" name="WSRPRegistrationService">
         <soap:address location="https://localhost:8443/portal-wsrp/RegistrationService"/>
      </wsdl:port>

      <wsdl:port binding="bind:WSRP_v1_PortletManagement_Binding_SOAP" name="WSRPPortletManagementService">
         <soap:address location="https://localhost:8443/portal-wsrp/PortletManagementService"/>
      </wsdl:port>
   </wsdl:service>-->
</wsdl:definitions>
